# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99dc4f8df9da20e605e5c2abfe5e7ab99d8589c09b78ed0ee3443c15294faef6cb5fa671cc0e6137fde243ca5c429e6a6c82f20dbdae5f3ead79e64e55063e09

test:
  secret_key_base: 4c93a0a8678acdb0a40c0183f071444926794cf07e188c2981a97791502db55486d0c2ef6d4691e2f3326194d42f40adfdcd560bec0196274eec51b4b854b354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
